Lab_4/Models/ErrorViewModel.cs
using System;

namespace Lab_4.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

Lab_4/Models/Hire.cs
using System;
using System.Collections.Generic;
using System.ComponentModel;
using System.ComponentModel.DataAnnotations;
using System.ComponentModel.DataAnnotations.Schema;
using System.Linq;
using System.Threading.Tasks;

namespace Lab_4.Models
{
    public class Hire
    {
        [Key]
        public int HireId { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [Required(ErrorMessage ="Введіть будь ласка Ваше повне ім'я")]
        [DisplayName("ПІБ клієнта")]
        public string FullNameClient { get; set; }

        [Column(TypeName = "varchar(10)")]
        [DisplayName("Серія та номер паспорта")]
        public string ClientCode { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [DisplayName("Домашня адреса")]
        public string ClientAddress { get; set; }

        [Column(TypeName = "varchar(10)")]
        [Required(ErrorMessage = "Введіть будь ласка Ваш мобільний телефон")]
        [DisplayName("Контактний телефон")]
        public string ClientPhone { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [Required(ErrorMessage = "Введіть будь ласка назву товару")]
        [DisplayName("Назва товару")]
        public string NameGoods { get; set; }

        [Column(TypeName = "nvarchar(250)")]
        [DisplayName("Опис товару")]
        public string DescriptionGoods { get; set; }

        [Column(TypeName = "int")]
        [Required(ErrorMessage = "Введіть будь ласка ціну товару")]
        [DisplayName("Ціна товару")]
        public int PriceGoods { get; set; }

        [Column(TypeName = "datetime")]
        [DisplayName("Дата видачі")]
        public DateTime DateIssue { get; set; }

        [Column(TypeName = "datetime")]
        [DisplayName("Дата повернення")]
        public DateTime DateReturn { get; set; }

        [Column(TypeName = "int")]
        [DisplayName("Вартість прокату за добу")]
        public int PriceHireOnDay { get; set; }
    }
}

Lab_4/Models/HireContext.cs
using Microsoft.EntityFrameworkCore;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;

namespace Lab_4.Models
{
    public class HireContext:DbContext
    {
        public HireContext(DbContextOptions<HireContext> options):base(options)
        {

        }

        public DbSet<Hire> Hire { get; set; }
    }
}

Lab_4/Controllers/HireController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using Lab_4.Models;

namespace Lab_4.Controllers
{
    public class HireController : Controller
    {
        private readonly HireContext _context;

        public HireController(HireContext context)
        {
            _context = context;
        }

        // GET: Hire
        public async Task<IActionResult> Index()
        {
            return View(await _context.Hire.ToListAsync());
        }

        // GET: Hire/Create
        public IActionResult AddOrEdit(int id=0)
        {
            if(id == 0)
            {
                return View(new Hire());
            }

            else
            {
                return View(_context.Hire.Find(id));
            }
                
        }

        // POST: Hire/Create
        // To protect from overposting attacks, please enable the specific properties you want to bind to, for 
        // more details see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> AddOrEdit([Bind("HireId,FullNameClient,ClientCode,ClientAddress,ClientPhone,NameGoods,DescriptionGoods,PriceGoods,DateIssue,DateReturn,PriceHireOnDay")] Hire hire)
        {
            if (ModelState.IsValid)
            {
                if(hire.HireId == 0)
                    _context.Add(hire);
                else
                    _context.Update(hire);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            return View(hire);
        }

        // GET: Hire/Delete/5
        public async Task<IActionResult> Delete(int? id)
        {
            var hire = await _context.Hire.FindAsync(id);
            _context.Hire.Remove(hire);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
    }
}

Lab_4/Controllers/HomeController.cs
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Lab_4.Models;

namespace Lab_4.Controllers
{
    public class HomeController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

Lab_4/Views/Hire/AddOrEdit.cshtml
@model Lab_4.Models.Hire

@{
    ViewData["Title"] = "Create";
}

<h4>Прокат товарів</h4>
<hr />
<div class="row">
    <div class="col-md-6">
        <form asp-action="AddOrEdit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="HireId"/>
            <div class="form-group">
                <label asp-for="FullNameClient" class="control-label">ПІБ клієнта</label>
                <input asp-for="FullNameClient" class="form-control" />
                <span asp-validation-for="FullNameClient" class="text-danger"></span>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="ClientCode" class="control-label">Серія та номер паспорта</label>
                    <input asp-for="ClientCode" class="form-control" />
                    <span asp-validation-for="ClientCode" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="ClientPhone" class="control-label">Контактний телефон</label>
                    <input asp-for="ClientPhone" class="form-control" />
                    <span asp-validation-for="ClientPhone" class="text-danger"></span>
                </div>
            </div>

            <div class="form-group">
                <label asp-for="ClientAddress" class="control-label">Домашня адреса</label>
                <input asp-for="ClientAddress" class="form-control" />
                <span asp-validation-for="ClientAddress" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="NameGoods" class="control-label">Назва товару</label>
                <input asp-for="NameGoods" class="form-control" />
                <span asp-validation-for="NameGoods" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="DescriptionGoods" class="control-label">Опис товару</label>
                <input asp-for="DescriptionGoods" class="form-control" />
                <span asp-validation-for="DescriptionGoods" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="PriceGoods" class="control-label">Ціна товару</label>
                <input asp-for="PriceGoods" class="form-control" />
                <span asp-validation-for="PriceGoods" class="text-danger"></span>
            </div>

            <div class="form-row">
                <div class="form-group col-md-6">
                    <label asp-for="DateIssue" class="control-label">Дата видачі</label>
                    <input asp-for="DateIssue" class="form-control" />
                    <span asp-validation-for="DateIssue" class="text-danger"></span>
                </div>
                <div class="form-group col-md-6">
                    <label asp-for="DateReturn" class="control-label">Дата повернення</label>
                    <input asp-for="DateReturn" class="form-control" />
                    <span asp-validation-for="DateReturn" class="text-danger"></span>
                </div>
            </div>
                
            <div class="form-group">
                <label asp-for="PriceHireOnDay" class="control-label">Вартість прокату за добу</label>
                <input asp-for="PriceHireOnDay" class="form-control" />
                <span asp-validation-for="PriceHireOnDay" class="text-danger"></span>
            </div>
            <div class="form-row">
                <div class="form-group col-md-5">
                    <input type="submit" value="Створити" class="btn btn-primary btn-block" />
                </div>
                <div class="form-group col-md-7">
                    <a asp-action="Index" class="btn btn-secondary btn-block"><i class="fa fa-table"></i> Повернутися до списку замовлень</a>
                </div>
            </div>
        </form>
    </div>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Lab_4/Views/Hire/Index.cshtml
@model IEnumerable<Lab_4.Models.Hire>

@{
    ViewData["Title"] = "Index";
}

<h4>Прокат товарів</h4>
<hr />

<table class="table table-hover table-bordered">
    <thead>
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.FullNameClient)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientCode)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientAddress)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ClientPhone)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.NameGoods)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DescriptionGoods)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceGoods)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateIssue)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.DateReturn)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.PriceHireOnDay)
            </th>
            <th>
                <a asp-action="AddOrEdit" class="btn btn-outline-success"><i class="far fa-plus-square"></i> Нове замовлення</a>
            </th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model) {
                <tr>
                    <td>
                        @Html.DisplayFor(modelItem => item.FullNameClient)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClientCode)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClientAddress)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.ClientPhone)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.NameGoods)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DescriptionGoods)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PriceGoods)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateIssue)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.DateReturn)
                    </td>
                    <td>
                        @Html.DisplayFor(modelItem => item.PriceHireOnDay)
                    </td>
                    <td>
                        <a asp-action="AddOrEdit" asp-route-id="@item.HireId"><i class="fa fa-marker fa-lg"></i></a> 
                        <a asp-action="Delete" asp-route-id="@item.HireId" class="text-danger ml-1" onclick="return confirm('Видалити даний запис?')"><i class="fa fa-trash-alt fa-lg"></i></a>
                    </td>
                </tr>
         }
    </tbody>
</table>

Lab_4/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

Lab_4/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Lab_4</title>

    <environment include="Development">
        <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.css" />
    </environment>
    <environment exclude="Development">
        <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css"
              asp-fallback-href="~/lib/bootstrap/dist/css/bootstrap.min.css"
              asp-fallback-test-class="sr-only" asp-fallback-test-property="position" asp-fallback-test-value="absolute"
              crossorigin="anonymous"
              integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" />
    </environment>
    <link rel="stylesheet" href="~/css/site.css" />
    <link rel="stylesheet" href="https://use.fontawesome.com/releases/v5.8.1/css/all.css" integrity="sha384-50oBUHEmvpQ+1lW4y57PTFmhCaXp0ML5d60M1M7uH2+nqUivzIebhndOJK28anvf" crossorigin="anonymous">
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">Lab_4</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Hire" asp-action="Index">Прокат</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <partial name="_CookieConsentPartial" />
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2019 - Lab_4 - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>

    <environment include="Development">
        <script src="~/lib/jquery/dist/jquery.js"></script>
        <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.js"></script>
    </environment>
    <environment exclude="Development">
        <script src="https://cdnjs.cloudflare.com/ajax/libs/jquery/3.3.1/jquery.min.js"
                asp-fallback-src="~/lib/jquery/dist/jquery.min.js"
                asp-fallback-test="window.jQuery"
                crossorigin="anonymous"
                integrity="sha256-FgpCb/KJQlLNfOu91ta32o/NMZxltwRo8QtmkMRdAu8=">
        </script>
        <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.bundle.min.js"
                asp-fallback-src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"
                asp-fallback-test="window.jQuery && window.jQuery.fn && window.jQuery.fn.modal"
                crossorigin="anonymous"
                integrity="sha384-xrRywqdh3PHs8keKZN+8zzc5TX0GRTLCcmivcbNJWm2rs5C8PRhcEn3czEjhAO9o">
        </script>
    </environment>
    <script src="~/js/site.js" asp-append-version="true"></script>

    @RenderSection("Scripts", required: false)
</body>
</html>